=== lkrubner/ams_sample_xml/ams_xml_schemas_2021-09/AMS_846_XML_V002.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 sp1 (x64) (http://www.altova.com) by Marco Pelaez (Private) -->
<!-- W3C Schema generated by XMLSpy v2019 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ClientCode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="WI"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DataDate">
		<xs:simpleType>
			<xs:restriction base="xs:date">
				<xs:enumeration value="2018-01-23"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DataTime">
		<xs:simpleType>
			<xs:restriction base="xs:time">
				<xs:enumeration value="09:30:47-08:00"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Document">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DocumentType"/>
				<xs:element ref="Version"/>
				<xs:element ref="ClientCode"/>
				<xs:element ref="DataDate"/>
				<xs:element ref="DataTime"/>
				<xs:element ref="InventoryItems"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DocumentType">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="846"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="InventoryItem">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemNumber"/>
				<xs:element ref="UPC"/>
				<xs:element ref="LocationQtys"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="InventoryItems">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InventoryItem" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ItemNumber">
		<xs:simpleType>
			<xs:restriction base="xs:long">
				<xs:enumeration value="6789054321"/>
				<xs:enumeration value="8763042342"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Location">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Main"/>
				<xs:enumeration value="SCO3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LocationQty">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Location"/>
				<xs:element ref="QTYAvailable"/>
				<xs:element ref="QTYInWarehouse"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LocationQtys">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="LocationQty" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QTYAvailable">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="10"/>
				<xs:enumeration value="12"/>
				<xs:enumeration value="99"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="QTYInWarehouse">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="10"/>
				<xs:enumeration value="12"/>
				<xs:enumeration value="99"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="UPC">
		<xs:simpleType>
			<xs:restriction base="xs:long">
				<xs:enumeration value="8976542312"/>
				<xs:enumeration value="8976543567"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Version">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="V002"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== lkrubner/ams_sample_xml/ams_xml_schemas_2021-09/AMS_846_XML_V002.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2020 sp1 (x64) (http://www.altova.com)-->
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AMS_846_XML_V002.xsd">
	<DocumentType>846</DocumentType>
	<Version>V002</Version>
	<ClientCode>WI</ClientCode>
	<DataDate>2018-01-23</DataDate>
	<DataTime>09:30:47-08:00</DataTime>
	<InventoryItems>
		<InventoryItem>
			<ItemNumber>6789054321</ItemNumber>
			<UPC>8976542312</UPC>
			<LocationQtys>
				<LocationQty>
					<Location>Main</Location>
					<QTYAvailable>10</QTYAvailable>
					<QTYInWarehouse>10</QTYInWarehouse>
				</LocationQty>
				<LocationQty>
					<Location>SCO3</Location>
					<QTYAvailable>12</QTYAvailable>
					<QTYInWarehouse>12</QTYInWarehouse>
				</LocationQty>
			</LocationQtys>
		</InventoryItem>
		<InventoryItem>
			<ItemNumber>8763042342</ItemNumber>
			<UPC>8976543567</UPC>
			<LocationQtys>
				<LocationQty>
					<Location>Main</Location>
					<QTYAvailable>99</QTYAvailable>
					<QTYInWarehouse>99</QTYInWarehouse>
				</LocationQty>
				<LocationQty>
					<Location>SCO3</Location>
					<QTYAvailable>10</QTYAvailable>
					<QTYInWarehouse>10</QTYInWarehouse>
				</LocationQty>
			</LocationQtys>
		</InventoryItem>
	</InventoryItems>
</Document>
