=== lkrubner/ams_sample_xml/ams_xml_schemas_2021-09/AMS_943_XML_V001.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2019 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ArrivalDate">
		<xs:simpleType>
			<xs:restriction base="xs:date">
				<xs:enumeration value="2018-02-01"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ClientCode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="WI"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ContainerNumber">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="TestContainerNumber"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DataDate">
		<xs:simpleType>
			<xs:restriction base="xs:date">
				<xs:enumeration value="2018-01-01"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DataTime">
		<xs:simpleType>
			<xs:restriction base="xs:time">
				<xs:enumeration value="09:30:00-08:00"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Document">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DocumentType"/>
				<xs:element ref="Version"/>
				<xs:element ref="ClientCode"/>
				<xs:element ref="DataDate"/>
				<xs:element ref="DataTime"/>
				<xs:element ref="InboundPO"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DocumentType">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="943"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="InboundPO">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="InboundPOHeader"/>
				<xs:element ref="References"/>
				<xs:element ref="LineItems"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="InboundPOHeader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PurchaseOrderNumber"/>
				<xs:element ref="Location"/>
				<xs:element ref="ArrivalDate"/>
				<xs:element ref="POType"/>
				<xs:element ref="ContainerNumber"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ItemNumber">
		<xs:simpleType>
			<xs:restriction base="xs:long">
				<xs:enumeration value="6789054321"/>
				<xs:enumeration value="6789054322"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LineID">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LineItem">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemNumber"/>
				<xs:element ref="UPC"/>
				<xs:element ref="QTY"/>
				<xs:element ref="QTYUOM"/>
				<xs:element ref="LineID"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LineItems">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="LineItem" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Location">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="WIT2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="POType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Receipt"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PurchaseOrderNumber">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="TestPoNumber"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="QTY">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="10"/>
				<xs:enumeration value="101"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="QTYUOM">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="EA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Reference">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ReferenceQualifier"/>
				<xs:element ref="ReferenceText"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ReferenceQualifier">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="String"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ReferenceText">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="String"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="References">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Reference"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UPC">
		<xs:simpleType>
			<xs:restriction base="xs:long">
				<xs:enumeration value="8976543567"/>
				<xs:enumeration value="8976543568"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Version">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="V001"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== lkrubner/ams_sample_xml/ams_xml_schemas_2021-09/AMS_943_XML_V001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 (x64) (http://www.altova.com) by Marco Pelaez (Private) -->
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Users/jirwin/Dropbox/AMSFulfillment/XML_Specs/AMS_943_XML_V001.xsd">
	<DocumentType>943</DocumentType>
	<Version>V001</Version>
	<ClientCode>WI</ClientCode>
	<DataDate>2018-01-01</DataDate>
	<DataTime>09:30:00-08:00</DataTime>
	<InboundPO>
		<InboundPOHeader>
			<PurchaseOrderNumber>TestPoNumber</PurchaseOrderNumber>
			<Location>WIT2</Location>
			<ArrivalDate>2018-02-01</ArrivalDate>
			<POType>Receipt</POType>
			<ContainerNumber>TestContainerNumber</ContainerNumber>
		</InboundPOHeader>
		<References>
			<Reference>
				<ReferenceQualifier>String</ReferenceQualifier>
				<ReferenceText>String</ReferenceText>
			</Reference>
		</References>
		<LineItems>
			<LineItem>
				<ItemNumber>6789054321</ItemNumber>
				<UPC>008976543567</UPC>
				<QTY>10</QTY>
				<QTYUOM>EA</QTYUOM>
				<LineID>01</LineID>
			</LineItem>
			<LineItem>
				<ItemNumber>6789054322</ItemNumber>
				<UPC>008976543568</UPC>
				<QTY>101</QTY>
				<QTYUOM>EA</QTYUOM>
				<LineID>01</LineID>
			</LineItem>
		</LineItems>
	</InboundPO>
</Document>
